name: pytask-julia

channels:
  - conda-forge
  - conda-forge/label/pytask_rc
  - conda-forge/label/pytask_parallel_rc
  - nodefaults

dependencies:
  - python =3.12
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - julia
  - pytask >=0.4.0
  - pytask-parallel >=0.4.0

  # Optional package dependencies
  - pyyaml

  # Misc
  - black
  - bumpversion
  - jupyterlab
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda

  - pip:
    - -e .
