name: pytask-julia

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - julia
  - pytask >=0.2
  - pytask-parallel >=0.1

  # Optional package dependencies
  - pyyaml

  # Misc
  - black
  - bumpversion
  - jupyterlab
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda

  - pip:
    - -e .
